name: findstack
description: "An app that shows what other apps are built with"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/white-findstack-bg-black.png" # Standard icon
  adaptive_icon_background: "#000000" # Pure black layer
  adaptive_icon_foreground: "assets/icons/white-findstack-nobg.png" # Floating logo layer

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/vectors/
  fonts:
    - family: UncutSans
      fonts:
        - asset: assets/fonts/UncutSans-Variable.ttf
